FROM debian:jessie
RUN DEBIAN_FRONTEND=noninteractive apt-get update -yq && apt-get install -yq --no-install-recommends \
        apt-utils \
        apt-transport-https \
        ca-certificates \
        curl \
        && echo "deb https://packages.sury.org/php/ jessie main" > /etc/apt/sources.list.d/php.list \
        && curl -o apt.gpg https://packages.sury.org/php/apt.gpg \
        && apt-key add apt.gpg \
        && rm apt.gpg \
        && apt-get update -yq && apt-get install -yq \
            php7.0-cli \
            php7.0-pgsql \
            php7.0-mysql \
            php7.0-gd \
            php7.0-intl \
            php7.0-mbstring \
            php7.0-xml \
            php7.0-memcached \
            php7.0-xdebug \
            php7.0-bcmath \
            php7.0-zip \
            php7.0-curl \
        && apt-get autoremove \
        && apt-get autoclean
CMD ["php -a"]